### PR TITLE
add strip_base_path

### PR DESCRIPTION
**Pull request by jaehyeon-kim**
PR to handle non-root base path of API Gateway custom domain.

Details can be found in https://github.com/erm/mangum/issues/78

### CODE REVIEW

**Comment by erm** [comment]
@jaehyeon-kim thanks! 

Could you also include a test for this so it passes the build?

**Comment by erm** [comment]
@jaehyeon-kim I'm happy to merge these changes if we can get the changes tested. Do you need any assistance with this?

**Comment by jaehyeon-kim** [comment]
Hi @erm 

Can you please check the test case? https://github.com/jaehyeon-kim/mangum/blob/feature/apig-base-path/tests/test_http.py#L404

Cheers,
Jaehyeon

**Comment by erm** [comment]
@jaehyeon-kim all good, thanks!

**Pull request merged**
